# Generated by Django 4.0.5 on 2022-07-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='img/product/')),
            ],
        ),
    ]
