# Generated by Django 4.0.5 on 2022-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_shortdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=80, null=True)),
                ('Subject', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(error_messages={'unique': 'Please enter your email address.'}, max_length=80, null=True)),
                ('Message', models.TextField(null=True)),
            ],
        ),
    ]
